services:
  api:
    build: ../api
    environment:
      - REDIS_URL=redis://redis:6379/0
      - ARTIFACTS_DIR=/data/artifacts
      - INLINE_JOB_EXEC=${INLINE_JOB_EXEC:-}
    ports:
      - "8000:8000"
    depends_on:
      - redis
    command: uvicorn api.app.main:app --host 0.0.0.0 --port 8000
    volumes:
      - artifacts:/data/artifacts

  frontend:
    build:
      context: ..
      dockerfile: frontend/Dockerfile
      args:
        - API_BASE_URL=http://localhost:8000
    ports:
      - "8080:80"
    depends_on:
      - api

  frontend-dev:
    image: node:20-alpine
    working_dir: /app
    volumes:
      - ../frontend:/app
    environment:
      - VITE_API_PROXY_TARGET=http://api:8000
    command: sh -c "npm install && npm run dev -- --host 0.0.0.0 --port 5173"
    ports:
      - "5173:5173"
    depends_on:
      - api
    profiles: ["dev"]

  worker:
    build:
      context: ..
      dockerfile: workers/Dockerfile
    environment:
      - REDIS_URL=redis://redis:6379/0
      - ARTIFACTS_DIR=/data/artifacts
      - QUEUE=jobs
    depends_on:
      - redis
    volumes:
      - artifacts:/data/artifacts

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

volumes:
  artifacts:
