name: CI

on:
  push:
    branches: ["**"]
  pull_request:

permissions:
  contents: read

jobs:
  backend:
    name: Backend Lint & Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
          cache-dependency-path: api/pyproject.toml

      - name: Install dependencies
        run: |
          python -m pip install -U pip
          python -m pip install -e "api[dev]"

      - name: Lint (ruff)
        run: ruff check api

      - name: Type check (mypy)
        run: mypy api

      - name: Run tests (pytest)
        run: pytest -q api

  frontend:
    name: Frontend Typecheck & Build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Typecheck (tsc)
        run: npx tsc --noEmit -p tsconfig.json

      - name: Build (vite)
        run: npm run build

  e2e:
    name: E2E (Playwright)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json

      - name: Install Playwright dependencies
        working-directory: frontend
        run: |
          npm ci
          npx playwright install --with-deps

      - name: Start API and Frontend (Docker Compose)
        env:
          INLINE_JOB_EXEC: '1'
        run: |
          docker compose -f infra/docker-compose.yml up -d api frontend
          echo "Waiting for API...";
          for i in {1..60}; do curl -sf http://localhost:8000/health && break || sleep 2; done
          echo "Waiting for Frontend...";
          for i in {1..60}; do curl -sf http://localhost:8080 && break || sleep 2; done

      - name: Run Playwright tests
        working-directory: frontend
        env:
          E2E_BASE_URL: http://localhost:8080
        run: npx playwright test --reporter=line

      - name: Print Docker logs on failure
        if: failure()
        run: |
          docker compose -f infra/docker-compose.yml ps
          docker compose -f infra/docker-compose.yml logs --no-color --tail=200 api frontend

      - name: Shutdown services
        if: always()
        run: docker compose -f infra/docker-compose.yml down -v
